# Bandit configuration for traffic system
skips: ['B311', 'B101']  # Skip random and assert_used
exclude_dirs: ['tests', 'venv', '.venv', '__pycache__']
confidence: medium  # Only report medium and high confidence issues
severity: medium    # Only report medium and high severity issues
