name: Simple CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

env:
  PYTHON_VERSION: '3.9'

jobs:
  # Simple Unit Tests
  unit-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic pytest pytest-cov
    
    - name: Run basic tests
      run: |
        python -m pytest tests/unit/test_ci_smoke.py -v
    
    - name: Run unit tests
      run: |
        python -m pytest tests/unit/ -v --tb=short

  # Simple Code Quality
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8
    
    - name: Code formatting check
      run: black --check --diff src/ tests/
    
    - name: Linting
      run: flake8 src/ tests/ --max-line-length=88 --extend-ignore=E203,W503

  # Simple API Tests
  api-tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install fastapi uvicorn pydantic pytest httpx
    
    - name: Start API server
      run: |
        uvicorn src.api.main:app --host 0.0.0.0 --port 8000 &
        sleep 10
    
    - name: Run API tests
      run: |
        python -m pytest tests/api/ -v --tb=short 